### ISSUE TITLE
handle non ascii title and user

### ISSUE THREAD

**Issue by jvschiavo** [iamtalhaasghar/yewtube#52]
## Issue / Suggestion

Following the README suggestion I did:
`set columns user:14 date comments rating likes dislikes category:9 views`
but got some messy results in the view:

![image](https://user-images.githubusercontent.com/20977075/156907287-99239599-3a70-4600-be03-a2be62faeb53.png)

As you can see, I have no comments, rating, likes, dislikes or category fields. The date and Viiew fields are also displaying differently from the screenshot in the README.md file.
There is also a misalignment problem on the line 27, the one with hindi characters

I did `set columns user:14 date comments rating likes dislikes category:9 views`, then tried to do a search.

## Your Environment

```
OS: Debian 11 bullseye
Kernel: x86_64 Linux 5.10.0-11-amd64
```

`bash: mpsyt: command not found`
Although `yt --version` returns:
```
yewtube version    : 2.8.0
yt_dlp version     : 2022.02.04
Python version     : 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/my_user/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : pt_BR.UTF-8
```

Debian 11 bullseye

mpv 0.32.0

**Comment by rachmadaniHaryono** [comment]
comments is not working right now, because yewtube moved from pafy

like and dislike also not working, but there is effort here

https://github.com/iamtalhaasghar/yewtube/blob/d7fa4e914d138152f2e1ee92726a18d46f3f144b/mps_youtube/pafy.py#L119-L120

it should also be applied to search command

basically the issue

- columns not working, comment count, rating(?), like, dislike, category, view
- handle non ascii title and user
- update screenshot
- date column (`26/11/12` or `7 months`)

**Comment by iamtalhaasghar** [comment]
Likes, Dislikes & category can be viewed using `i 1` command.
Similarly comments can be viewed using `c 1` command.
Fetching likes, dislikes for every video on serp is a costly operation and takes too much time.
