### ISSUE TITLE
scoop package  or cli pacakge for window 

### ISSUE THREAD

**Issue by happuji** [iamtalhaasghar/yewtube#82]
i been using scoop for everythign 

it would be good if  i can have  [`scoop.`](scoop.sh) pakage of yewtube too 

:O 

thx for yewtube also

**Comment by iamtalhaasghar** [comment]
See #72

**Comment by happuji** [comment]
bruh that was not i was wanting

**Comment by iamtalhaasghar** [comment]
I simply don't have time an energy to spend on to build, package and distribute `yewtube` as a separate package in major operating systems (windows / debian / fedora / arch etc).
However, `yewtube` users can host such packages on their distro repos and I can add link them in this repo so that others can benefit from them as well.

**Comment by lonix1** [comment]
Multiple package manager options would be nice, but as @iamtalhaasghar stated, would be lots of work.

A compromise would be some widely-used package manager, like flatpak.
